name: CrateKeyVault
main: net.craftersland.crate.CKV
version: 1.4.3
author: CraftersLand
website: www.craftersland.net
load: POSTWORLD
depend: [HolographicDisplays, EffectLib]
description: Crate key vaults.
api-version: 1.13
commands:
    ckv:
        description: The main command
permissions:
    CKV.admin:
        description: Admin commands access
        default: op
    CKV.open:
        description: Admin commands to access other player vault.
        default: op